[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "itpu"
version = "0.0.1"
description = "Information-Theoretic Processing Unit — software SDK (pre-alpha)"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "ITPU Team" }]
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.23",
  "scipy>=1.10",
  "numba>=0.58",
  "matplotlib>=3.7",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["itpu*"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
