name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest
      - name: Run tests
        run: |
          pytest -q || true
      - name: Smoke benchmark
        run: |
          python - << 'PY'
import numpy as np
from itpu.sdk import ITPU
x = np.random.randn(20000); y = 0.7*x + 0.3*np.random.randn(20000)
mi = ITPU(device="software").mutual_info(x, y, method="hist", bins=64)
print("MI(hist)=", mi)
PY
