name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Tests (${{ matrix.os }} / py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -e .
          pip install pytest numpy scipy scikit-learn matplotlib
      - name: Run tests
        run: pytest -q

  eeg_smoke:
    name: EEG benchmark smoke (Ubuntu / py3.11)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -e .
          pip install pytest numpy scipy scikit-learn matplotlib
      - name: Run headless EEG benchmark
        env:
          MPLBACKEND: Agg
        run: |
          python - <<'PY'
          from examples.eeg_realtime_dashboard import BenchmarkComparison
          bc = BenchmarkComparison()
          bc.run(duration_s=10, n_channels=6, fs=200)
          print("EEG benchmark smoke: OK")
          PY
